### ISSUE TITLE
can someone guide me?

### ISSUE THREAD

**Issue by ghostingone** [yarrm80s/orpheusdl#10]
i'm kinda lost because i don't know much of how phyton works, if somebody could help me, i would be really grateful! :)

**Comment by z0rg0n** [comment]
That looks like you're not in the folder where you cloned the repository using `git clone https://github.com/yarrm80s/orpheusdl.git && cd orpheusdl` either that you you never cloned it.
  
Note that those commands are for Linux and you're on windows so it may not work exactly. You should still be able to install and use git though.

**Comment by ghostingone** [comment]
i managed to install the requirements
![image](https://user-images.githubusercontent.com/95058949/158492859-f4d03a05-e8e8-4fde-b608-9e75dfc5d91f.png)

however, i pasted the code for the settings there and that happened
![image](https://user-images.githubusercontent.com/95058949/158492959-bfb76466-da95-48a5-a81b-8777db062277.png)

i also tried to run the orpheusdl file and the module on phyton (3.9), but they ain't working. Thank you for your time!

![image](https://user-images.githubusercontent.com/95058949/158493318-48fee98b-b9d4-4a7e-8c1d-619d4f1d1c84.png)
![image](https://user-images.githubusercontent.com/95058949/158493460-656b173d-154f-47c0-b435-139ee3e255c4.png)

**Comment by z0rg0n** [comment]
You need to install a module for whatever streaming subscription you have.
For example if you use Tidal you would install [this module](https://github.com/Dniel97/orpheusdl-tidal).

**Comment by Dniel97** [comment]
OrpheusDL does not include any module by default, you have to manually install modules, for example [OrpheusDL Qobuz](https://github.com/yarrm80s/orpheusdl-qobuz) or [OrpheusDL Tidal](https://github.com/Dniel97/orpheusdl-tidal).

**Comment by z0rg0n** [comment]
I don't think that's it. I don't have access to my box as a reference but I'm pretty sure the login info goes in `orpheusdl/config/settings.json` at the bottom of the file.

**Comment by ghostingone** [comment]
ik where it is but i don't find where i need to put my credentials :/ ![image](https://user-images.githubusercontent.com/95058949/158698486-9fe6d618-34f8-442c-971e-f5a7ea4a55cf.png)

**Comment by Dniel97** [comment]
After cloning a module in `modules/` you have to execute `python orpheus.py` as stated in every module's README.md to refresh the `config/settings.json` file. After the refresh, the required options needed for the module to work properly will be added.

**Comment by ghostingone** [comment]
i did this and it didn't added anything :/
the only thing that i found related to login was this 
![image](https://user-images.githubusercontent.com/95058949/158704411-b4f216d7-afcf-4f32-bef3-6d0eaa5b02ea.png)

**Comment by Dniel97** [comment]
I'm not sure which module you are trying to use, but if you are using the OrpheusDL Tidal module, just exeute `python orpheus.py <tidal link here>` as shown in the [Usage Example](https://github.com/Dniel97/orpheusdl-tidal#usage).

**Comment by ghostingone** [comment]
thank you so much, i finally got to download it! one final question, do you know how to separate the channels from this file on audacity? it shows me a error bc of the ffmpeg library, but i already have them installed on my PC

![image](https://user-images.githubusercontent.com/95058949/158708950-dd35dc68-6a9a-4e4c-ad2b-06650dc337a0.png)

**Comment by Dniel97** [comment]
That's not related to OrpheusDL, therefore off-topic. Closing.
