### ISSUE TITLE
Cannot setup tidal module

### ISSUE THREAD

**Issue by pdhlnpt** [yarrm80s/orpheusdl#11]
Hello. I tried to install orpheusdl for my mac. I cannot install orpheusdl.
When I run this command 
`pip install -r requirements.txt `
I got this error: 
` zsh: command not found: pip`

I tried to google and tried to install pip on my Mac and my Mac already have pip-22.0.4
How can I move on?

**Comment by z0rg0n** [comment]
Maybe try `pip3 install -r requirements.txt`

**Comment by pdhlnpt** [comment]
> Maybe try `pip3 install -r requirements.txt`

Hello I can move on with your help but after that when I tried to install tidal module followed the instruction:
```
Clone the repo inside the folder orpheusdl/modules/
git clone https://github.com/Dniel97/orpheusdl-tidal.git tidal
Execute:
python orpheus.py
```
I got a problem with 
``` python orpheus.py``` 
like this:
```
File "orpheus.py", line 70
    raise Exception(f'Unknown setting "{modulesetting}" for module "{setting}"')
                                                                              ^
SyntaxError: invalid syntax
```
How can I move on now? 
Thanks

**Comment by z0rg0n** [comment]
OrpheusDL does not include any module by default, you have to manually install modules, for example [OrpheusDL Qobuz](https://github.com/yarrm80s/orpheusdl-qobuz) or [OrpheusDL Tidal](https://github.com/Dniel97/orpheusdl-tidal).*
  
*See https://github.com/yarrm80s/orpheusdl/issues/10

**Comment by pdhlnpt** [comment]
> OrpheusDL does not include any module by default, you have to manually install modules, for example [OrpheusDL Qobuz](https://github.com/yarrm80s/orpheusdl-qobuz) or [OrpheusDL Tidal](https://github.com/Dniel97/orpheusdl-tidal).*
> 
> *See #10

sure I know that So that I'm trying to install a tidal module but I got an error after clone the tidal module git. I cannot run the ```python orpheus.py```  when installing tidal module.

**Comment by pdhlnpt** [comment]
> My bad, I misread your post. Bumpy car ride.
> 
> Did you edit the configuration file to add your login info?

Im geting stuck at installing the tidal module ( step ```python orpheus.py```) so that I dont think I have the configuration file to edit my tidal login. :(

**Comment by z0rg0n** [comment]
Did you run `python3 orpheus.py settings refresh` from the install instructions here: https://github.com/yarrm80s/orpheusdl?

**Comment by pdhlnpt** [comment]
> 

Ofcourse I did it before I tried to install tidal module. 
```

   ____             _                    _____  _      
  / __ \           | |                  |  __ \| |     
 | |  | |_ __ _ __ | |__   ___ _   _ ___| |  | | |     
 | |  | | '__| '_ \| '_ \ / _ \ | | / __| |  | | |     
 | |__| | |  | |_) | | | |  __/ |_| \__ \ |__| | |____ 
  \____/|_|  | .__/|_| |_|\___|\__,_|___/_____/|______|
             | |                                       
             |_|                                       
             

No modules are installed, quitting
```

**Comment by z0rg0n** [comment]
I think you have to do it after installing the modules so the config file has the right fields in it.

**Comment by pdhlnpt** [comment]
I tried to follow and finished to step 3 in 
```https://github.com/yarrm80s/orpheusdl```
and after that I tried to follow and finished the step 1 in
``` https://github.com/Dniel97/orpheusdl-tidal```
and now Im stuck in step 2. I don't know what I do wrong 🤕

**Comment by z0rg0n** [comment]
The configuration file is in `orpheusdl/config` and the name of the file is `settings.json`. From your description I think the file will be there and at the bottom of it it should have a spot to enter your Tidal longin information.
  
Is the settings.json file there?
Is there a place to enter your Tidal login information at the bottom?
Did you enter the login information at the bottom?

**Comment by pdhlnpt** [comment]
I got only "config" folder in "/Users/******/orpheusdl/orpheusdl" and there is nothing inside "config" folder.

**Comment by z0rg0n** [comment]
If the config folder is empty then you never got step 3 right in `https://github.com/yarrm80s/orpheusdl`.  This step creates the settings file.

**Comment by pdhlnpt** [comment]
> If the config folder is empty then you never got step 3 right in `https://github.com/yarrm80s/orpheusdl`. This step creates the settings file.
I already did it before I moved on to install tidal module :(

[https://imgur.com/myk66Ah](url)
[https://imgur.com/2URTniT](url)

**Comment by z0rg0n** [comment]
It appears you installed orpheusdl twice once in `/orpheusdl` and once in `/orpheusdl/orpheusdl` so there could be an issue there with which installation you're running.
  
The other issue is it looks like the tidal module isn't installed in `/modules`. Although not as sure about this one without being able to compare it to my installation.
  
I suggest deleting it all and starting over. Don't create a folder called orpheusdl just run the clone command right in your parent folder. Be sure each command you run you're in the correct folder when you run it. Ie `/modules` or `/orpheusdl`.

**Comment by pdhlnpt** [comment]
> It appears you installed orpheusdl twice once in `/orpheusdl` and once in `/orpheusdl/orpheusdl` so there could be an issue there with which installation you're running.
> 
> The other issue is it looks like the tidal module isn't installed in `/modules`. Although not as sure about this one without being able to compare it to my installation.
> 
> I suggest deleting it all and starting over. Don't create a folder called orpheusdl just run the clone command right in your parent folder. Be sure each command you run you're in the correct folder when you run it. Ie `/orpheusdl/modules` or `/orpheusdl`.

OK I will delete all folder include orpheusdl in my Mac and retry now. let's see the result

**Comment by z0rg0n** [comment]
Not sure why that's not working. The only thing I can think of trying is using `pip3` or `python` instead of `pip` or `python3` but from my (limited) understanding of your terminals output that shouldn't matter.

**Comment by pdhlnpt** [comment]
> Not sure why that's not working. The only thing I can think of trying is using `pip3` or `python` instead of `pip` or `python3` but from my (limited) understanding of your terminals output that shouldn't matter.

Thanks anyway. I will try to find the way to fix it. Thanks

**Comment by Dniel97** [comment]
> > If the config folder is empty then you never got step 3 right in `https://github.com/yarrm80s/orpheusdl`. This step creates the settings file.
> > I already did it before I moved on to install tidal module :(
> 
> [https://imgur.com/myk66Ah](url) [https://imgur.com/2URTniT](url)

You installed Orpheus in the first Orpheus folder. As @z0rg0n already said you have to use `pip3` and `python3` on macOS and you should have one `orpheusdl/` folder with a subfolder `orpeusdl/modules/` where you install all your modules, so you should have `orpheusdl/modules/tidal/` for example.

**Comment by Dniel97** [comment]
No update, closing.
