### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by drossosc** [yarrm80s/orpheusdl#13]
Hello. Just following the installation guide, when I got hit with this

Traceback (most recent call last):
  File "/Users/drossos/Desktop/orpheusdl/orpheus.py", line 6, in <module>
    from orpheus.core import *
  File "/Users/drossos/Desktop/orpheusdl/orpheus/core.py", line 4, in <module>
    from orpheus.music_downloader import Downloader
  File "/Users/drossos/Desktop/orpheusdl/orpheus/music_downloader.py", line 5, in <module>
    from ffmpeg import Error
ImportError: cannot import name 'Error' from 'ffmpeg' (/opt/homebrew/lib/python3.9/site-packages/ffmpeg/__init__.py)

Here are my installed 'pip' packages:

Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.12
defusedxml         0.7.1
ffmpeg-python      0.2.0
future             0.18.2
idna               3.3
importlib          1.0.4
mutagen            1.45.1
Pillow             9.1.0
pip                22.1
protobuf           3.20.1
pycryptodomex      3.14.1
requests           2.27.1
setuptools         49.2.1
tqdm               4.64.0
urllib3            1.26.9

**Comment by Dniel97** [comment]
Try to delete `ffmpeg-python` with 

```sh
pip uninstall ffmpeg-python
```

also make sure to use the right `pip` command for your python version. For example use 

```sh
python3 -m pip list
python3 -m pip install -r requirements.txt
```

to use the right `pip` command corresponding to your `python` command.

**Comment by satsurfer** [comment]
C:\orpheusdl>**pip install -r requirements.txt**
Requirement already satisfied: defusedxml>=0.7.1 in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 1)) (0.7.1)
Requirement already satisfied: protobuf>=3.15.8 in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 2)) (4.21.1)
Requirement already satisfied: pycryptodomex>=3.10.1 in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 3)) (3.14.1)
Requirement already satisfied: requests>=2.25.1 in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 4)) (2.28.0)
Requirement already satisfied: Pillow>=8.2.0 in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 5)) (9.1.1)
Requirement already satisfied: tqdm>=4.60.0 in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 6)) (4.61.0)
Requirement already satisfied: mutagen>=1.45.1 in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 7)) (1.45.1)
Requirement already satisfied: ffmpeg-python>=0.2.0 in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 8)) (0.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.25.1->-r requirements.txt (line 4)) (2.10)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.25.1->-r requirements.txt (line 4)) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.25.1->-r requirements.txt (line 4)) (1.25.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.25.1->-r requirements.txt (line 4)) (2020.6.20)
Requirement already satisfied: future in c:\users\satsu\appdata\local\programs\python\python38\lib\site-packages (from ffmpeg-python>=0.2.0->-r requirements.txt (line 8)) (0.18.2)
**WARNING: There was an error checking the latest version of pip.**

**Comment by satsurfer** [comment]
C:\orpheusdl>**python3 orpheus.py settings refresh**
Traceback (most recent call last):
  File "C:\orpheusdl\orpheus.py", line 6, in <module>
    from orpheus.core import *
  File "C:\orpheusdl\orpheus\core.py", line 1, in <module>
    import importlib, json, logging, os, pickle, requests, urllib3, base64, shutil
ModuleNotFoundError: No module named 'requests'

**Comment by Dniel97** [comment]
> C:\orpheusdl>**python3 orpheus.py settings refresh** Traceback (most recent call last): File "C:\orpheusdl\orpheus.py", line 6, in from orpheus.core import * File "C:\orpheusdl\orpheus\core.py", line 1, in import importlib, json, logging, os, pickle, requests, urllib3, base64, shutil ModuleNotFoundError: No module named 'requests'

If you are using `python3` you lost likely have to use `pip3 install -r requirements.txt` or `python3 -m pip install -r requirements.txt`.

**Comment by Dniel97** [comment]
> Where is detailled decribed how to put in my Tidal/Qobuz account? thx.

That compelety depends on the modules, so you have to look at the modules `README.md`: [Qobuz](https://github.com/yarrm80s/orpheusdl-qobuz#qobuz) and OrpheusDL-Tidal uses the TV with flow by default so it will request the account when entering any Tidal URL.
