### ISSUE TITLE
No modules are installed, quitting

### ISSUE THREAD

**Issue by yallhearsumn** [yarrm80s/orpheusdl#14]
Hello, I already installed all of the stuff and all the modules but it says this:

![image](https://user-images.githubusercontent.com/67226248/169272535-aa8030d8-c9bb-4e13-b6f0-52f98be001b9.png)

**Comment by yarrm80s** [comment]
@yallhearsumn you haven't installed them properly, send an image of the tree of the root folder where orpheus.py is

**Comment by yallhearsumn** [comment]
> @yallhearsumn you haven't installed them properly, send an image of the tree of the root folder where orpheus.py is

![image](https://user-images.githubusercontent.com/67226248/169273092-c3ffbf8b-be46-46c4-9366-8daf23ba750f.png)
do you mean this?

**Comment by yarrm80s** [comment]
@yallhearsumn no I mean the tree command

**Comment by yallhearsumn** [comment]
![image](https://user-images.githubusercontent.com/67226248/169273300-da5ee7d2-beaa-41c8-953b-69368b30ece5.png)

**Comment by yarrm80s** [comment]
@yallhearsumn you haven't installed any modules...? What did you do to "install" them?

**Comment by yallhearsumn** [comment]
i simply did the python -m pip install -r requirements.txt

**Comment by yallhearsumn** [comment]
how can I even install the modules into that folder? @yarrm80s

**Comment by yarrm80s** [comment]
@yallhearsumn there are links to the modules you can install on t.me/orpheusdl, read the pinned message for them. There are instructions for installation on their readme's

**Comment by yallhearsumn** [comment]
> @yallhearsumn there are links to the modules you can install on t.me/orpheusdl, read the pinned message for them. There are instructions for installation on their readme's

okay, thank you for your help. i'll update this soon

**Comment by yallhearsumn** [comment]
it's working now, thank you so much for your help. closing the issue

**Comment by yarrm80s** [comment]
@yallhearsumn yeah sure no problem :)
