### ISSUE TITLE
Mention modules in the README

### ISSUE THREAD

**Issue by tacohitbox** [yarrm80s/orpheusdl#17]
I don't know if you leave this out for legal reasons or something but people I've sent this program pretty much always get confused after the installation process because a config file doesn't generate without you having a module installed.

I can make a PR to notice but I wanted to see if it was for legal reasons or if the documentation was out of date or something.

**Comment by yarrm80s** [comment]
@tacohitbox well, the entire point of OrpheusDL was to separate the main downloader from the DMCA breaking modules 🤷

**Comment by yarrm80s** [comment]
also to make adding new services significantly easier, but as a main benefit was the separation of the most important and time consuming to write code from the DMCA parts

**Comment by yarrm80s** [comment]
If you want to find all the modules though, the list is in our Telegram group t.me/orpheusdl

**Comment by tacohitbox** [comment]
> @tacohitbox well, the entire point of OrpheusDL was to separate the main downloader from the DMCA breaking modules shrug

i get that but i think you should atleast mention the fact they exist to prevent confusion. that's my only complaint though, amazing project otherwise :)
