### ISSUE TITLE
Receiving error "Warning: Track download failed: 'url'" for specific URL

### ISSUE THREAD

**Issue by z0rg0n** [yarrm80s/orpheusdl#18]
I tried running this URL:
https://open.qobuz.com/album/q1o6jkf1uoppb

and received this error for each track (apart from track and 13):
```
                Downloading track file
                Warning: Track download failed: 'url'
        === Track 165494697 failed ===
```

Other URLs seem to be working fine.

It's newly updated with `git pull`

**Comment by yarrm80s** [comment]
@z0rg0n Please turn on debug mode in the settings and send the full error message

**Comment by z0rg0n** [comment]
Output:
`DEBUG:root:Orpheus: Modules detected: tidal, example, qobuz
DEBUG:root:Orpheus: tidal added as a module
DEBUG:root:Orpheus: example added as a module
DEBUG:root:Orpheus: qobuz added as a module
DEBUG:root:Orpheus: qobuz module has been loaded
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.qobuz.com:443
DEBUG:urllib3.connectionpool:https://www.qobuz.com:443 "GET /api.json/0.2/album/get?album_id=q1o6jkf1uoppb&app_id=950096963&extra=albumsFromSameArtist%2CfocusAll HTTP/1.1" 200 None
=== Downloading album 11:11 (q1o6jkf1uoppb) ===
        Artist: Regina Spektor (42740)
        Year: 2001
        Number of tracks: 33
        Service: Qobuz
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): static.qobuz.com:443
DEBUG:urllib3.connectionpool:https://static.qobuz.com:443 "GET /images/covers/pb/op/q1o6jkf1uoppb_max.jpg HTTP/1.1" 200 2297420

        Track 1/33
        === Downloading track Love Affair (165494665) ===
                Artists: Regina Spektor (42740)
                Release year: 2001
                Codec: FLAC, bit depth: 16bit, sample rate: 44.1kHz
                Track file already exists
        === Track 165494665 skipped ===

        Track 2/33
        === Downloading track Rejazz (165494666) ===
                Artists: Regina Spektor (42740)
                Release year: 2001
                Codec: FLAC, bit depth: 16bit, sample rate: 44.1kHz

                Downloading track file
DEBUG:urllib3.connectionpool:https://www.qobuz.com:443 "GET /api.json/0.2/track/getFileUrl?track_id=165494666&format_id=27&intent=stream&sample=false&app_id=950096963&user_auth_token=xnR3uKly1-X2aOOLmsDJBtIrbuG1QXBKGCSVWXHtAFas-EjhZW--HEADu3g-ICpyE9SgH0XWha2BUY2zExHahg&request_ts=1660274066&request_sig=e8472e3b427537e7a804113217be4e60 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "orpheus.py", line 223, in <module>
    main()
  File "orpheus.py", line 218, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "/home/closetmusic/orpheusdl/orpheus/core.py", line 389, in orpheus_core_download
    downloader.download_album(media_id, extra_kwargs=media.extra_kwargs)
  File "/home/closetmusic/orpheusdl/orpheus/music_downloader.py", line 172, in download_album
    self.download_track(track_id, album_location=album_path, track_index=index, number_of_tracks=number_of_tracks, main_artist=artist_name, cover_temp_location=cover_temp_location, indent_level=indent_level+1, extra_kwargs=album_info.track_extra_kwargs)
  File "/home/closetmusic/orpheusdl/orpheus/music_downloader.py", line 315, in download_track
    download_info: TrackDownloadInfo = self.service.get_track_download(**track_info.download_extra_kwargs)
  File "/home/closetmusic/orpheusdl/modules/qobuz/interface.py", line 101, in get_track_download
    return TrackDownloadInfo(download_type=DownloadEnum.URL, file_url=self.session.get_file_url(track_id, quality_tier)['url'])
KeyError: 'url'
`

**Comment by z0rg0n** [comment]
Figured it out.

Tracks aren't available yet.

My bad.
