### ISSUE TITLE
No Modules are installed quitting

### ISSUE THREAD

**Issue by SI0209** [yarrm80s/orpheusdl#2]
I installed orpheusdl with the modules and whenever I'm running it using python, it shows the logo but is saying the message typed above. But I'm running it with python and not python3, could that be the reason, if so, I tried to run it using python3 but wasn't running at all.

**Comment by Dniel97** [comment]
You have to install a module such as: [https://github.com/Dniel97/orpheusdl-tidal](https://github.com/Dniel97/orpheusdl-tidal). Just download the master zip and place the unzipped `orpheusdl-tidal-master` folder in `orpheus/modules/`, rename it to `tidal` for convenience and then use `python orpheus.py` (if you are using Windows?). If you are more advanced, just follow the installation instructions ;)

**Comment by Dniel97** [comment]
No further information provided, closing. Feel free to open it again.
