### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by jasontkenny** [yarrm80s/orpheusdl#51]
`C:\Users\jason\OrpheusDL>python3 orpheus.py settings refresh
Traceback (most recent call last):
  File "C:\Users\jason\OrpheusDL\orpheus.py", line 7, in <module>
    from orpheus.core import *
  File "C:\Users\jason\OrpheusDL\orpheus\core.py", line 1, in <module>
    import importlib, json, logging, os, pickle, requests, urllib3, base64, shutil
ModuleNotFoundError: No module named 'requests'`

**Comment by uhwot** [comment]
@jasontkenny run "pip install -r requirements.txt"

**Comment by jasontkenny** [comment]
@uhwot already did

**Comment by uhwot** [comment]
@jasontkenny try this then
"python3 -m pip install -r requirements.txt"

**Comment by jasontkenny** [comment]
@uhwot worked, thank you
