### ISSUE TITLE
No modules are installed, quitting

### ISSUE THREAD

**Issue by jasontkenny** [yarrm80s/orpheusdl#52]
`C:\Users\jason\OrpheusDL>python3 orpheus.py settings refresh

   ____             _                    _____  _
  / __ \           | |                  |  __ \| |
 | |  | |_ __ _ __ | |__   ___ _   _ ___| |  | | |
 | |  | | '__| '_ \| '_ \ / _ \ | | / __| |  | | |
 | |__| | |  | |_) | | | |  __/ |_| \__ \ |__| | |____
  \____/|_|  | .__/|_| |_|\___|\__,_|___/_____/|______|
             | |
             |_|

No modules are installed, quitting`

**Comment by wesleywmgMMU** [comment]
i oso having this problem

**Comment by dwrekofc** [comment]
also having this issue. anyone figure out a solution?

**Comment by OrfiDev** [comment]
I only really now realised how unclear the readme is on this, but you need to install OrpheusDL modules first. Zero code for interacting with specific services is included in the base app.
