### ISSUE TITLE
help me for edit settng.json

### ISSUE THREAD

**Issue by Dragonfoce** [yarrm80s/orpheusdl#53]
hi i would like to know that if create folder artist/album when download how to edit?

**Comment by brennankapollock** [comment]
i'm not entirely sure of what you're asking but in the settings.json you can set the specific path structure for how a track or artist gets populated in your target downloads folder.

**Comment by Dniel97** [comment]
Sure its simple as:
```json
        "formatting": {
            "album_format": "{artist}/{name}{explicit}",
            "force_album_format": true
        }
```
