### ISSUE TITLE
Ffmpeg is not installed or is not working!

### ISSUE THREAD

**Issue by mostlite** [yarrm80s/orpheusdl#55]
When i tried to download music on flac 24bitup not mqa, it says ffmpeg is not installed or not working! I have this issue because it converts to m4a but i wanna have it on flac any solutions?

**Comment by toddchan1713** [comment]
I am running an error message
![Uploading WechatIMG275.jpg…]()

**Comment by toddchan1713** [comment]
I am running an error message
![WechatIMG275](https://github.com/OrfiTeam/OrpheusDL/assets/117327020/14c9028c-45f0-4821-bc01-02a4fcea5be4)

**Comment by OrfiDev** [comment]
> When i tried to download music on flac 24bitup not mqa, it says ffmpeg is not installed or not working! I have this issue because it converts to m4a but i wanna have it on flac any solutions?

Make sure FFMPEG is installed, and in your PATH. If you do not know how to do this, ask ChatGPT (genuinely, it gives very good explanations).

**Comment by RyanEskridge** [comment]
@OrfiTeam, Do you want help cleaning up open issues? There are many open issues that do not seem to be active.

**Comment by Dniel97** [comment]
> @OrfiTeam, Do you want help cleaning up open issues? There are many open issues that do not seem to be active.

Yeah you are right, cleaning up!
