### ISSUE TITLE
No features?

### ISSUE THREAD

**Issue by ququip123** [yarrm80s/orpheusdl#56]
Is there any way to add the features to the track name/artist?  For example downloading https://tidal.com/browse/track/4875690?u will show Pusha T in the CLI, but when I play the file it doesn't show his name as an artist or in the song title, here's my settings.json:

{
    "global": {
        "general": {
            "download_path": "./downloads/",
            "download_quality": "hifi",
            "search_limit": 10
        },
        "artist_downloading": {
            "return_credited_albums": true,
            "separate_tracks_skip_downloaded": true
        },
        "formatting": {
            "album_format": "{name}",
            "playlist_format": "{name}",
            "track_filename_format": "{name}",
            "single_full_path_format": "{name}",
            "enable_zfill": true,
            "force_album_format": false
        },
        "codecs": {
            "proprietary_codecs": true,
            "spatial_codecs": true
        },
        "module_defaults": {
            "lyrics": "default",
            "covers": "default",
            "credits": "default"
        },
        "lyrics": {
            "embed_lyrics": true,
            "embed_synced_lyrics": false,
            "save_synced_lyrics": true
        },
        "covers": {
            "embed_cover": true,
            "main_compression": "low",
            "main_resolution": 1400,
            "save_external": false,
            "external_format": "png",
            "external_compression": "low",
            "external_resolution": 5000,
            "save_animated_cover": true
        },
        "playlist": {
            "save_m3u": true,
            "paths_m3u": "absolute",
            "extended_m3u": true
        },
        "advanced": {
            "advanced_login_system": false,
            "codec_conversions": {
                "alac": "flac",
                "wav": "flac"
            },
            "conversion_flags": {
                "flac": {
                    "compression_level": "0"
                }
            },
            "conversion_keep_original": false,
            "cover_variance_threshold": 8,
            "debug_mode": false,
            "disable_subscription_checks": false,
            "enable_undesirable_conversions": false,
            "ignore_existing_files": false,
            "ignore_different_artists": true
        }
    },
    "extensions": {},
    "modules": {
        "tidal": {
            "tv_atmos_token": "xxxxx",
            "tv_atmos_secret": "xxxxx=",
            "mobile_atmos_hires_token": "xxxxxx",
            "mobile_hires_token": "xxxxxxx",
            "enable_mobile": true,
            "prefer_ac4": false,
            "fix_mqa": true
        }
    }
}

**Comment by RyanEskridge** [comment]
This is something that needs to be implemented by the Tidal module. Make a feature request here: https://github.com/Dniel97/orpheusdl-tidal

**Comment by Dniel97** [comment]
Please use MP3TAG to check the file for artist and title name. It could very well be that your player cannot show them.

**Comment by Dniel97** [comment]
No further activity, closing.
