### ISSUE TITLE
Multithreaded downloading for artists/albums/playlists

### ISSUE THREAD

**Issue by xbufu** [yarrm80s/orpheusdl#62]
As I have several larger playlists and like to hoard music in general, are there any plans on adding concurreny or multithreading? Something like async await?

**Comment by OrfiDev** [comment]
This would require a huge amount of rewriting code, so it remains as a feature for OrpheusDL's successor project, which has been trapped in the planning stage indefinitely due to a lack of motivation. Sorry :/
