### ISSUE TITLE
[FEATURE REQUEST] Create Portable Playlist files

### ISSUE THREAD

**Issue by CarterMoody** [yarrm80s/orpheusdl#68]
Playlist files should use relative paths instead of absolute paths. This is so that someone can download music, then move the entire folder and playlist files should not break.

**Comment by OrfiDev** [comment]
They were using absolute paths this whole time?!

**Comment by CarterMoody** [comment]
Annnnd I figured it out after a bit of trial and error. For anyone wondering, change "absolute" to "relative" in paths_m3u variable of settings.json 
![image](https://github.com/user-attachments/assets/55e580cc-6606-4e19-a0bc-839bc9d75ee8)

This setting is best complemented by these formatting settings which will dump everything into the same root level folder: 
![image](https://github.com/user-attachments/assets/bbf0bd13-e97d-43ff-8930-a8c956bd1ba5)

@OrfiDev  BTW is there a discord or telegram or anything for this community?

**Comment by OrfiDev** [comment]
Huh relative should really be the default, I don't remember why absolute was set as the default. Anyway, while we are in the process of moving to Discord, there is a Telegram group here: https://t.me/+wYTBb9sjyJwwMzNl
