### ISSUE TITLE
missing settings json file

### ISSUE THREAD

**Issue by gainl0078** [yarrm80s/orpheusdl#74]
Hello, i executed the command "python3 orpheus.py settings refresh", but nothing happens. And then i ran orpheus.py, i got a "config" folder, but still no settings.json under "config".

**Comment by cheesetosti** [comment]
Have you installed the requirements.txt + activated the venv (if you have any)?

**Comment by gainl0078** [comment]
Thx for reply. I installed the requirements.txt, activated the venv following the tutorial just now. is it correct? and how to do next?
![屏幕截图 2024-11-30 160213](https://github.com/user-attachments/assets/801f6f82-9117-4c44-ac49-e12d4f68a765)

**Comment by cheesetosti** [comment]
No settings.json inside the config folder? I have no idea :(

**Comment by Dniel97** [comment]
Do you use any OrpheusDL modules? You need to have one module at least installed for settings to be generated.

**Comment by gainl0078** [comment]
No, i started form the section "getting started", installed python environment of prerequisites, step 1,2,3 of installation, and stuck at step 4 because i don't have settings. 
How to install  module? Many thx.

**Comment by jamesy0ung** [comment]
> No, i started form the section "getting started", installed python environment of prerequisites, step 1,2,3 of installation, and stuck at step 4 because i don't have settings. How to install module? Many thx.

Find the module you want, for example orpheusdl-tidal and clone it into your modules folder

**Comment by gainl0078** [comment]
OH, I see.. Thx!
