### ISSUE TITLE
How to use album_id in album_format?

### ISSUE THREAD

**Issue by spencermathews** [yarrm80s/orpheusdl#9]
Thank you for this cool project.

I am trying to use the `{album_id}` variable in the `album_format` setting, but this leads to a `KeyError`. I see that `{album_id}` is documented as a variable for `track_filename_format`, but this does not make much sense.

Please allow `{album_id}` to be used in `album_format` because, well, `{album_id}` is actually a property of an album.

I'm using the Tidal module.

**Comment by Dniel97** [comment]
`album_format` has no key `{id}`, currently adding it ;)

**Comment by spencermathews** [comment]
Thank you!
